project:
  type: book
  output-dir: docs

execute: 
  execute-dir: project
  freeze: auto
  
book:
  title: "Book Template"
  author: 
    - Jane Doe
    - Who Else
  site-url: https://stefanthoma.github.io/en_quarto_template/
  date: today
  date-format: short
  chapters:
    - index.qmd
    - part: "Part 1"
      chapters:
        - chapters/intro.qmd
    - part: chapters/part2.qmd
      chapters:
        - chapters/summary.qmd
    - chapters/references.qmd
  downloads: pdf
  favicon: images/favicon.ico
  image: images/frontimage.png  


bibliography: ["bib/packages.bib", "bib/project.bib"]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
editor: source