project:
  type: book
  execute-dir: project
  output-dir: docs

lang: de 
execute: 
  freeze: auto
  
book:
  title: "Buch Template"
  author: 
    - Jane Doe
    - Who Else
  site-url: https://stefanthoma.github.io/de_quarto_template/
  date: today
  date-format: short
  chapters:
    - index.qmd
    - part: "Teil 1"
      chapters:
        - chapters/intro.qmd
    - part: chapters/teil2.qmd
      chapters:
        - chapters/summary.qmd
    - chapters/references.qmd
  downloads: pdf
  favicon: images/favicon.ico
  image: images/frontimage.png  


bibliography: ["bib/packages.bib", "bib/project.bib"]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
editor: source